AppBundle\Entity\Product:
    properties:
        designation:
            - NotBlank: ~
        eanCode:
            - NotBlank: ~
            - Type: integer
            - GreaterThan: 0

AppBundle\Entity\Offer:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['merchant', 'product']
    properties:
        price:
            - NotBlank: ~
            - Type: float
        updatedAt:
            - NotBlank: ~
            - Type: datetime
